In [1]:
import json
import csv
import numpy as np
import pandas as pd


In [2]:
import string

In [3]:
import re

# Converting review Json to pandas dataframe

In [4]:
outfile = open("review_stars.tsv","w")
sfile = csv.writer(outfile,delimiter="\t",quoting=csv.QUOTE_MINIMAL)
sfile.writerow(['business_id','stars','text'])

with open('yelp_academic_dataset_review.json',encoding="utf-8") as f:
    for line in f:
        row=json.loads(line)
        sfile.writerow([row['business_id'],row['stars'],(row['text']).encode('utf-8')])

outfile.close()

df = pd.read_csv('review_stars.tsv',delimiter="\t",encoding="utf-8")

In [5]:
df[:10]

business_id  stars  \
0  iCQpiavjjPzJ5_3gPD5Ebg      2   
1  pomGBqfbxcqPv14c3XH-ZQ      5   
2  jtQARsP6P-LbkyjbO1qNGg      1   
3  elqbBhBfElMNSrjFqW3now      2   
4  Ums3gaP2qM3W1XcA5r6SsQ      5   
5  vgfcTvK81oD4r50NMjU2Ag      1   
6  AxeQEz3-s9_1TyIo-G7UQw      5   
7  zdE82PiD6wquvjYLyhOJNA      5   
8  EAwh1OmG6t6p3nRaZOW_AA      4   
9  atVh8viqTj-sqDJ35tAYVg      2   

                                                text  
0  b"The pizza was okay. Not the best I've had. I...  
1  b'I love this place! My fiance And I go here a...  
2  b'Terrible. Dry corn bread. Rib tips were all ...  
3  b'Back in 2005-2007 this place was my FAVORITE...  
4  b'Delicious healthy food. The steak is amazing...  
5  b'This place sucks. The customer service is ho...  
6  b"If you like Thai food, you have to try the o...  
7  b'AMAZING!!!\n\n I was referred here by a frie...  
8  b'Ribs = amazing\n2 hour wait time= not so ama...  
9  b"Food is pretty good, not gonna lie. BUT you ...

In [6]:
df.text = df.text.apply(lambda x: x.lower()) #convert text to lower case

In [7]:
df.text = df.text.replace(r'\\n','', regex=True) #removing \n 

In [8]:
df[:10]

business_id  stars  \
0  iCQpiavjjPzJ5_3gPD5Ebg      2   
1  pomGBqfbxcqPv14c3XH-ZQ      5   
2  jtQARsP6P-LbkyjbO1qNGg      1   
3  elqbBhBfElMNSrjFqW3now      2   
4  Ums3gaP2qM3W1XcA5r6SsQ      5   
5  vgfcTvK81oD4r50NMjU2Ag      1   
6  AxeQEz3-s9_1TyIo-G7UQw      5   
7  zdE82PiD6wquvjYLyhOJNA      5   
8  EAwh1OmG6t6p3nRaZOW_AA      4   
9  atVh8viqTj-sqDJ35tAYVg      2   

                                                text  
0  b"the pizza was okay. not the best i've had. i...  
1  b'i love this place! my fiance and i go here a...  
2  b'terrible. dry corn bread. rib tips were all ...  
3  b'back in 2005-2007 this place was my favorite...  
4  b'delicious healthy food. the steak is amazing...  
5  b'this place sucks. the customer service is ho...  
6  b"if you like thai food, you have to try the o...  
7  b'amazing!!! i was referred here by a friend a...  
8  b'ribs = amazing2 hour wait time= not so amazi...  
9  b"food is pretty good, not gonna lie. but you ...

In [9]:
review_agg = df.groupby('business_id')['text'].sum() #it's series

In [10]:
df_review_agg = review_agg.to_frame().reset_index() #converting series to dataframe

In [11]:
df_review_agg[:10]

business_id                                               text
0  --1UhMGODdWsrMastO9DZw  b'came here for lunch last week and was pleasa...
1  --6MefnULPED_I942VcFNA  b"the incredibly rude woman behind the cashier...
2  --7zmmkVg-IMGaXbuVd0SQ  b'great beer, great place, excellent service f...
3  --8LPVSo5i0Oo61X01sV9A  b'dr. lacognata is great.  he is a great liste...
4  --9QQLMTbFzLJ_oT-ON3Xw  b"i've been going to this particular location ...
5  --9e1ONYQuAa-CB_Rrw7Tw  b"it was a real up and down evening.apps - bbq...
6  --DaPTJW3-tB1vP-PfdTEg  b"excellent and friendly service!  nice clean ...
7  --DdmeR16TRb3LsjG0ejrQ  b'i was really disappointed in this event. i b...
8  --EF5N7P70J_UYBTPypYlA  b"owner is not friendly and didn't appear to b...
9  --EX4rRznJrltyn-34Jz1w  b"it's bbw what can i say?! this location is i...

In [12]:
df_review_agg.shape

(188593, 2)

# Converting business json to dataframe

In [13]:
ratingfile = open("rating_stars.tsv","w")
rfile = csv.writer(ratingfile,delimiter="\t",quoting=csv.QUOTE_MINIMAL)
rfile.writerow(['business_id','stars','review_count'])

with open('yelp_academic_dataset_business.json',encoding="utf-8") as f:
    for line in f:
        row=json.loads(line)
        rfile.writerow([row['business_id'],row['stars'],row['review_count']])

ratingfile.close()

df_star = pd.read_csv('rating_stars.tsv',delimiter="\t",encoding="utf-8")

In [14]:
df_star[:10]

business_id  stars  review_count
0  Apn5Q_b6Nz61Tq4XzPdf9A    4.0            24
1  AjEbIBw6ZFfln7ePHha9PA    4.5             3
2  O8S5hYJ1SMc8fA4QBtVujA    4.0             5
3  bFzdJJ3wp3PZssNEsyU23g    1.5             8
4  8USyCYqpScwiNEb58Bt6CA    2.0             4
5  45bWSZtniwPRiqlivpS8Og    4.0            63
6  9A2quhZLyWk0akUetBd8hQ    4.0             7
7  6OuOZAok8ikONMS_T3EzXg    2.0             7
8  8-NRKkPY1UiFXW20WXKiXg    2.5            40
9  UTm5QZThPQlT35mkAcGOjg    3.5             3

In [15]:
df_star.shape

(188593, 3)

# Combining both the dataframe

In [16]:
df_combined = pd.merge(df_review_agg, df_star, on='business_id')

In [17]:
df_combined[:10]

business_id                                               text  \
0  --1UhMGODdWsrMastO9DZw  b'came here for lunch last week and was pleasa...   
1  --6MefnULPED_I942VcFNA  b"the incredibly rude woman behind the cashier...   
2  --7zmmkVg-IMGaXbuVd0SQ  b'great beer, great place, excellent service f...   
3  --8LPVSo5i0Oo61X01sV9A  b'dr. lacognata is great.  he is a great liste...   
4  --9QQLMTbFzLJ_oT-ON3Xw  b"i've been going to this particular location ...   
5  --9e1ONYQuAa-CB_Rrw7Tw  b"it was a real up and down evening.apps - bbq...   
6  --DaPTJW3-tB1vP-PfdTEg  b"excellent and friendly service!  nice clean ...   
7  --DdmeR16TRb3LsjG0ejrQ  b'i was really disappointed in this event. i b...   
8  --EF5N7P70J_UYBTPypYlA  b"owner is not friendly and didn't appear to b...   
9  --EX4rRznJrltyn-34Jz1w  b"it's bbw what can i say?! this location is i...   

   stars  review_count  
0    4.0            24  
1    3.0            39  
2    4.0            54  
3    3.5             4  
4    3.5            11  
5    4.0          1546  
6    3.5            45  
7    3.0             5  
8    3.0             5  
9    4.0             4

In [18]:
df_combined.shape

(188593, 4)

# Normalizing the review_count using zscore

In [19]:
from scipy.stats import zscore
df_combined['normalized_review_count'] = zscore(df_combined['review_count'])
df_combined[:10]

business_id                                               text  \
0  --1UhMGODdWsrMastO9DZw  b'came here for lunch last week and was pleasa...   
1  --6MefnULPED_I942VcFNA  b"the incredibly rude woman behind the cashier...   
2  --7zmmkVg-IMGaXbuVd0SQ  b'great beer, great place, excellent service f...   
3  --8LPVSo5i0Oo61X01sV9A  b'dr. lacognata is great.  he is a great liste...   
4  --9QQLMTbFzLJ_oT-ON3Xw  b"i've been going to this particular location ...   
5  --9e1ONYQuAa-CB_Rrw7Tw  b"it was a real up and down evening.apps - bbq...   
6  --DaPTJW3-tB1vP-PfdTEg  b"excellent and friendly service!  nice clean ...   
7  --DdmeR16TRb3LsjG0ejrQ  b'i was really disappointed in this event. i b...   
8  --EF5N7P70J_UYBTPypYlA  b"owner is not friendly and didn't appear to b...   
9  --EX4rRznJrltyn-34Jz1w  b"it's bbw what can i say?! this location is i...   

   stars  review_count  normalized_review_count  
0    4.0            24                -0.074885  
1    3.0            39                 0.069174  
2    4.0            54                 0.213233  
3    3.5             4                -0.266964  
4    3.5            11                -0.199736  
5    4.0          1546                14.542311  
6    3.5            45                 0.126798  
7    3.0             5                -0.257360  
8    3.0             5                -0.257360  
9    4.0             4                -0.266964

# Normalizing the review_count using min_max formula

In [20]:
min_count= df_combined['review_count'].min()
max_count= df_combined['review_count'].max()
df_combined['norm_min_max_review_count'] = ((df_combined['review_count']-min_count)/(max_count-min_count))

In [21]:
df_combined[:10]

business_id                                               text  \
0  --1UhMGODdWsrMastO9DZw  b'came here for lunch last week and was pleasa...   
1  --6MefnULPED_I942VcFNA  b"the incredibly rude woman behind the cashier...   
2  --7zmmkVg-IMGaXbuVd0SQ  b'great beer, great place, excellent service f...   
3  --8LPVSo5i0Oo61X01sV9A  b'dr. lacognata is great.  he is a great liste...   
4  --9QQLMTbFzLJ_oT-ON3Xw  b"i've been going to this particular location ...   
5  --9e1ONYQuAa-CB_Rrw7Tw  b"it was a real up and down evening.apps - bbq...   
6  --DaPTJW3-tB1vP-PfdTEg  b"excellent and friendly service!  nice clean ...   
7  --DdmeR16TRb3LsjG0ejrQ  b'i was really disappointed in this event. i b...   
8  --EF5N7P70J_UYBTPypYlA  b"owner is not friendly and didn't appear to b...   
9  --EX4rRznJrltyn-34Jz1w  b"it's bbw what can i say?! this location is i...   

   stars  review_count  normalized_review_count  norm_min_max_review_count  
0    4.0            24                -0.074885                   0.002637  
1    3.0            39                 0.069174                   0.004520  
2    4.0            54                 0.213233                   0.006403  
3    3.5             4                -0.266964                   0.000126  
4    3.5            11                -0.199736                   0.001004  
5    4.0          1546                14.542311                   0.193723  
6    3.5            45                 0.126798                   0.005273  
7    3.0             5                -0.257360                   0.000251  
8    3.0             5                -0.257360                   0.000251  
9    4.0             4                -0.266964                   0.000126

# Filtering the dataset based on review_count

In [22]:
df_combined_refined = df_combined[(df_combined.review_count>40) & (df_combined.review_count<4000)]

In [23]:
df_combined_refined.shape

(30283, 6)

In [24]:
df_combined_refined[:10]

business_id                                               text  \
2   --7zmmkVg-IMGaXbuVd0SQ  b'great beer, great place, excellent service f...   
5   --9e1ONYQuAa-CB_Rrw7Tw  b"it was a real up and down evening.apps - bbq...   
6   --DaPTJW3-tB1vP-PfdTEg  b"excellent and friendly service!  nice clean ...   
10  --FBCX-N37CMYDfs790Bnw  b'the bar is dark and smokey, but they have a ...   
14  --I7YYLada0tSLkORTHb5Q  b"my husband and i stopped here at random, and...   
20  --SrzpvFLwP_YFwB_Cetow  b"it's my first time writing review on yelp. b...   
28  --cZ6Hhc9F7VkKXxHMVZSQ  b'our family of five got the latin combo-- ful...   
30  --cjBEbXMI2obtaRHNSFrA  b'swindled of a $5 cover per head the doorman ...   
45  --qvQS4MigHPykD2GV0-zw  b'what a fantastic moving company! it was easy...   
47  --ujyvoQlwVoBgMYtADiLA  b'ok i have been here twice. both times were v...   

    stars  review_count  normalized_review_count  norm_min_max_review_count  
2     4.0            54                 0.213233                   0.006403  
5     4.0          1546                14.542311                   0.193723  
6     3.5            45                 0.126798                   0.005273  
10    4.0           125                 0.895113                   0.015317  
14    3.5            83                 0.491748                   0.010044  
20    3.5            44                 0.117194                   0.005148  
28    4.0           333                 2.892732                   0.041431  
30    3.0            63                 0.299669                   0.007533  
45    4.0            43                 0.107590                   0.005022  
47    3.5            71                 0.376500                   0.008537

In [25]:
df_combined_refined["text"] = df_combined_refined['text'].str.replace('[^\w\s]','') #removing punctuation 

C:\Users\Mardavkumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [26]:
df_combined_refined[:10]

business_id                                               text  \
2   --7zmmkVg-IMGaXbuVd0SQ  bgreat beer great place excellent service from...   
5   --9e1ONYQuAa-CB_Rrw7Tw  bit was a real up and down eveningapps  bbq sh...   
6   --DaPTJW3-tB1vP-PfdTEg  bexcellent and friendly service  nice clean re...   
10  --FBCX-N37CMYDfs790Bnw  bthe bar is dark and smokey but they have a fa...   
14  --I7YYLada0tSLkORTHb5Q  bmy husband and i stopped here at random and i...   
20  --SrzpvFLwP_YFwB_Cetow  bits my first time writing review on yelp but ...   
28  --cZ6Hhc9F7VkKXxHMVZSQ  bour family of five got the latin combo full r...   
30  --cjBEbXMI2obtaRHNSFrA  bswindled of a 5 cover per head the doorman sa...   
45  --qvQS4MigHPykD2GV0-zw  bwhat a fantastic moving company it was easy t...   
47  --ujyvoQlwVoBgMYtADiLA  bok i have been here twice both times were ver...   

    stars  review_count  normalized_review_count  norm_min_max_review_count  
2     4.0            54                 0.213233                   0.006403  
5     4.0          1546                14.542311                   0.193723  
6     3.5            45                 0.126798                   0.005273  
10    4.0           125                 0.895113                   0.015317  
14    3.5            83                 0.491748                   0.010044  
20    3.5            44                 0.117194                   0.005148  
28    4.0           333                 2.892732                   0.041431  
30    3.0            63                 0.299669                   0.007533  
45    4.0            43                 0.107590                   0.005022  
47    3.5            71                 0.376500                   0.008537

In [27]:
df_combined_refined['text'] = df_combined_refined['text'].str[1:] #getting rid of first b tricky !

C:\Users\Mardavkumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [28]:
df_combined_refined[:10]

business_id                                               text  \
2   --7zmmkVg-IMGaXbuVd0SQ  great beer great place excellent service from ...   
5   --9e1ONYQuAa-CB_Rrw7Tw  it was a real up and down eveningapps  bbq shr...   
6   --DaPTJW3-tB1vP-PfdTEg  excellent and friendly service  nice clean res...   
10  --FBCX-N37CMYDfs790Bnw  the bar is dark and smokey but they have a fan...   
14  --I7YYLada0tSLkORTHb5Q  my husband and i stopped here at random and i ...   
20  --SrzpvFLwP_YFwB_Cetow  its my first time writing review on yelp but i...   
28  --cZ6Hhc9F7VkKXxHMVZSQ  our family of five got the latin combo full ro...   
30  --cjBEbXMI2obtaRHNSFrA  swindled of a 5 cover per head the doorman saw...   
45  --qvQS4MigHPykD2GV0-zw  what a fantastic moving company it was easy to...   
47  --ujyvoQlwVoBgMYtADiLA  ok i have been here twice both times were very...   

    stars  review_count  normalized_review_count  norm_min_max_review_count  
2     4.0            54                 0.213233                   0.006403  
5     4.0          1546                14.542311                   0.193723  
6     3.5            45                 0.126798                   0.005273  
10    4.0           125                 0.895113                   0.015317  
14    3.5            83                 0.491748                   0.010044  
20    3.5            44                 0.117194                   0.005148  
28    4.0           333                 2.892732                   0.041431  
30    3.0            63                 0.299669                   0.007533  
45    4.0            43                 0.107590                   0.005022  
47    3.5            71                 0.376500                   0.008537

In [29]:
df_combined_refined['text'] = df_combined_refined['text'].str.replace('\d+', '') #removing digits

C:\Users\Mardavkumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [30]:
df_combined_refined[:10]

business_id                                               text  \
2   --7zmmkVg-IMGaXbuVd0SQ  great beer great place excellent service from ...   
5   --9e1ONYQuAa-CB_Rrw7Tw  it was a real up and down eveningapps  bbq shr...   
6   --DaPTJW3-tB1vP-PfdTEg  excellent and friendly service  nice clean res...   
10  --FBCX-N37CMYDfs790Bnw  the bar is dark and smokey but they have a fan...   
14  --I7YYLada0tSLkORTHb5Q  my husband and i stopped here at random and i ...   
20  --SrzpvFLwP_YFwB_Cetow  its my first time writing review on yelp but i...   
28  --cZ6Hhc9F7VkKXxHMVZSQ  our family of five got the latin combo full ro...   
30  --cjBEbXMI2obtaRHNSFrA  swindled of a  cover per head the doorman saw ...   
45  --qvQS4MigHPykD2GV0-zw  what a fantastic moving company it was easy to...   
47  --ujyvoQlwVoBgMYtADiLA  ok i have been here twice both times were very...   

    stars  review_count  normalized_review_count  norm_min_max_review_count  
2     4.0            54                 0.213233                   0.006403  
5     4.0          1546                14.542311                   0.193723  
6     3.5            45                 0.126798                   0.005273  
10    4.0           125                 0.895113                   0.015317  
14    3.5            83                 0.491748                   0.010044  
20    3.5            44                 0.117194                   0.005148  
28    4.0           333                 2.892732                   0.041431  
30    3.0            63                 0.299669                   0.007533  
45    4.0            43                 0.107590                   0.005022  
47    3.5            71                 0.376500                   0.008537

In [31]:
from nltk.corpus import stopwords

In [32]:
from nltk.stem.porter import PorterStemmer

In [33]:
stop_words = stopwords.words('english')
porter = PorterStemmer()

In [34]:
#remove stop words
df_combined_refined['text']=df_combined_refined['text'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))

C:\Users\Mardavkumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [35]:
df_combined_refined[:20]

business_id                                               text  \
2   --7zmmkVg-IMGaXbuVd0SQ  great beer great place excellent service women...   
5   --9e1ONYQuAa-CB_Rrw7Tw  real eveningapps bbq shrimp great theres dont ...   
6   --DaPTJW3-tB1vP-PfdTEg  excellent friendly service nice clean restaura...   
10  --FBCX-N37CMYDfs790Bnw  bar dark smokey fantastic patio food good lot ...   
14  --I7YYLada0tSLkORTHb5Q  husband stopped random must say food drinks wa...   
20  --SrzpvFLwP_YFwB_Cetow  first time writing review yelp disgusted dish ...   
28  --cZ6Hhc9F7VkKXxHMVZSQ  family five got latin combo full rotisserie ch...   
30  --cjBEbXMI2obtaRHNSFrA  swindled cover per head doorman saw cash walle...   
45  --qvQS4MigHPykD2GV0-zw  fantastic moving company easy schedule time wr...   
47  --ujyvoQlwVoBgMYtADiLA  ok twice times poor first time server barely c...   
52  -01XupAWZEXbdNbxNg5mEg  amazing place relax grab bitedrink kids skatin...   
54  -050d_XIor1NpCuWkbIVaQ  one best breakfast places phoenix arrived late...   
57  -092wE7j5HZOogMLAh40zA  tonight first time ordered wongs food tastes n...   
58  -0BxAGlIk5DJAGVkpqBXxg  think awesome able find coffee bean las vegas ...   
61  -0DET7VdEQOJVJ_v6klEug  service terrible waited hour half table mentio...   
73  -0NrB58jqKqJfuUCDupcsw  craving kfc recently dropped work beat rush ge...   
77  -0Sgh0QlUKVsWosCWJzGqQ  worst dominos world also lyndsi worst server l...   
80  -0WegMt6Cy966qlDKhu6jA  quite good across ballpark easy access game di...   
83  -0ZO00Vm2ADchytlEkoXmg  loved experience lori wonderful son months lit...   
96  -0qht1roIqleKiQkBLDkbw  went cafebar pool charged onion rings went tel...   

    stars  review_count  normalized_review_count  norm_min_max_review_count  
2     4.0            54                 0.213233                   0.006403  
5     4.0          1546                14.542311                   0.193723  
6     3.5            45                 0.126798                   0.005273  
10    4.0           125                 0.895113                   0.015317  
14    3.5            83                 0.491748                   0.010044  
20    3.5            44                 0.117194                   0.005148  
28    4.0           333                 2.892732                   0.041431  
30    3.0            63                 0.299669                   0.007533  
45    4.0            43                 0.107590                   0.005022  
47    3.5            71                 0.376500                   0.008537  
52    3.0            82                 0.482144                   0.009918  
54    4.0           698                 6.398170                   0.087257  
57    3.5            89                 0.549371                   0.010797  
58    3.0            43                 0.107590                   0.005022  
61    3.0            98                 0.635807                   0.011927  
73    3.5            94                 0.597391                   0.011425  
77    2.0            44                 0.117194                   0.005148  
80    2.0            85                 0.510955                   0.010295  
83    5.0            77                 0.434124                   0.009291  
96    3.0           365                 3.200059                   0.045449

# Making the corpus ready for Tf-IDF vectorizer

In [36]:
review_list_all_business=[]
for review_text_per_business in df_combined_refined.text:
    review_list_all_business.append(review_text_per_business)

In [37]:
normalized_all_review_count=[]
for each_review_count in df_combined_refined.normalized_review_count:
    normalized_all_review_count.append(np.array(each_review_count))

In [38]:
all_star_rating = []
for each_rating in df_combined_refined.stars:
    all_star_rating.append(each_rating)

In [39]:
normalized_min_max_review_count=[]
for each_review_count in df_combined_refined.norm_min_max_review_count:
    normalized_min_max_review_count.append(each_review_count)

In [40]:
print(len(review_list_all_business))
print(len(normalized_all_review_count))
print(len(all_star_rating))
print(len(normalized_min_max_review_count))

30283
30283
30283
30283


# TF-IDF Vectorizer 

In [41]:
import sklearn.feature_extraction.text as sk_text

vectorizer = sk_text.TfidfVectorizer(
                             stop_words='english',
                             max_features = 1000,
                             min_df=1)
matrix = vectorizer.fit_transform(review_list_all_business)

print(type(matrix))          # Compressed Sparse Row matrix
print(matrix.toarray())        #  convert it to numpy array

print(vectorizer.get_feature_names())

<class 'scipy.sparse.csr.csr_matrix'>
[[ 0.01238766  0.          0.         ...,  0.02298303  0.          0.        ]
 [ 0.01504604  0.01833247  0.00602515 ...,  0.01837454  0.00964583
   0.01316916]
 [ 0.          0.00742313  0.02173539 ...,  0.01402186  0.          0.01004956]
 ..., 
 [ 0.00625911  0.          0.         ...,  0.04645052  0.          0.        ]
 [ 0.          0.00873945  0.         ...,  0.01650829  0.          0.        ]
 [ 0.00876081  0.00430243  0.0062989  ...,  0.01219056  0.00764999
   0.00582471]]
['able', 'absolutely', 'accommodating', 'actual', 'actually', 'add', 'added', 'addition', 'affordable', 'afternoon', 'ago', 'ahead', 'air', 'airport', 'amazing', 'ambiance', 'american', 'apparently', 'appetizer', 'appetizers', 'apple', 'appointment', 'appreciate', 'area', 'arent', 'arrived', 'asian', 'ask', 'asked', 'asking', 'ate', 'atmosphere', 'attention', 'attentive', 'attitude', 'authentic', 'available', 'average', 'avocado', 'avoid', 'away', 'awesome', 'awful'

In [42]:
array_1 = matrix.toarray()

In [43]:
array_2 = np.array([normalized_all_review_count])

In [44]:
array_2

array([[  0.2132333 ,  14.54231123,   0.12679784, ...,   0.34768845,
          0.1171939 ,   0.29966876]])

In [45]:
array_3 = np.concatenate((array_1, array_2.T),axis=1)

# Making X ready for the Models

In [46]:
X = array_3

In [47]:
X.shape

(30283, 1001)

In [48]:
array_4 = np.array([normalized_min_max_review_count])

# Making X for MultinomialNB

In [49]:
X_mnb = np.concatenate((array_1, array_4.T),axis=1)

In [50]:
X_mnb.shape

(30283, 1001)

# Making y ready for Linear Regression Model

In [51]:
y = np.array(all_star_rating)

In [52]:
y

array([ 4. ,  4. ,  3.5, ...,  3.5,  4. ,  3. ])

In [53]:
X.shape


(30283, 1001)

In [54]:
y.shape

(30283,)

In [55]:
y[:100]

array([ 4. ,  4. ,  3.5,  4. ,  3.5,  3.5,  4. ,  3. ,  4. ,  3.5,  3. ,
        4. ,  3.5,  3. ,  3. ,  3.5,  2. ,  2. ,  5. ,  3. ,  3.5,  3.5,
        4. ,  3.5,  4. ,  4.5,  3. ,  4.5,  3.5,  4. ,  1.5,  4.5,  3.5,
        3.5,  2.5,  4. ,  4. ,  4. ,  4. ,  4. ,  2.5,  3. ,  3.5,  4. ,
        4. ,  3. ,  3. ,  2.5,  4.5,  3.5,  4. ,  3. ,  4.5,  4. ,  3.5,
        4.5,  3.5,  3. ,  4.5,  3.5,  4. ,  4.5,  3.5,  3. ,  4. ,  3.5,
        4.5,  4. ,  4.5,  3.5,  3.5,  4.5,  3. ,  2.5,  4. ,  3.5,  3.5,
        3.5,  5. ,  3. ,  3. ,  3.5,  4. ,  3. ,  4. ,  4. ,  5. ,  4.5,
        4.5,  3.5,  3.5,  4. ,  4.5,  4. ,  4. ,  4. ,  3.5,  3. ,  3. ,
        4. ])

# Label Encoding y for classification Model

In [56]:
from sklearn import preprocessing
lb = preprocessing.LabelEncoder()
normalized_y=lb.fit_transform(y)
lb.classes_

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

In [57]:
normalized_y[:10]

array([6, 6, 5, 6, 5, 5, 6, 4, 6, 5], dtype=int64)

In [58]:
from sklearn import utils
print(utils.multiclass.type_of_target(normalized_y))

multiclass


# Splitting data into Train and Test data

In [59]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,normalized_y,test_size=0.25,random_state=1)

In [60]:
X_train_mnb,X_test_mnb,y_train_mnb,y_test_mnb = train_test_split(X_mnb,normalized_y,test_size=0.25,random_state=1)

In [61]:
X_train_lir,X_test_lir,y_train_lir,y_test_lir = train_test_split(X,y,test_size=0.25,random_state=1)

# Training  Different Models

In [62]:
from sklearn.naive_bayes import MultinomialNB

clf_mnb = MultinomialNB()
clf_mnb.fit(X_train_mnb, y_train_mnb)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [63]:
from sklearn.svm import SVC

clf_svc = SVC(C=10.0,kernel='linear')
clf_svc.fit(X_train,y_train)

SVC(C=10.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [64]:
from sklearn.neighbors import KNeighborsClassifier

clf_knn = KNeighborsClassifier(n_neighbors=10)
clf_knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=10, p=2,
           weights='uniform')

In [65]:
from sklearn.linear_model import LogisticRegression

clf_lr = LogisticRegression()
clf_lr.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [66]:
from sklearn.linear_model import LinearRegression

clf_lir = LinearRegression()
clf_lir.fit(X_train_lir, y_train_lir)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

# Testing and Evaluation

In [67]:
from sklearn import metrics

In [68]:
y_pred = clf_svc.predict(X_test)

print("test", y_test[:10])
print("pred", y_pred[:10])

print(metrics.confusion_matrix(y_test,y_pred))
print("Precision Score:: ",metrics.precision_score(y_test,y_pred,average='weighted'))   
print("Recall Score:: ",metrics.recall_score(y_test,y_pred,average='weighted'))      
print("F1 Score:: ",metrics.f1_score(y_test,y_pred,average='weighted')) 

test [6 5 8 5 6 7 5 6 6 4]
pred [6 6 8 5 6 6 6 5 5 4]
[[   2   11    1    0    0    0    0    0    0]
 [   5   36   45    1    0    0    0    0    0]
 [   0   15   90   72    3    0    0    0    0]
 [   0    0   33  286  109    2    0    0    0]
 [   0    0    3   86  718  261    3    0    0]
 [   0    0    0    3  175 1361  327    5    0]
 [   0    0    0    0    8  283 1732  195    0]
 [   0    0    0    0    0    5  252  947   85]
 [   0    0    0    0    0    0    0  122  289]]
Precision Score::  0.72035362651
Recall Score::  0.721304979527
F1 Score::  0.720308911265


# very Low F1 score  for SVM without parameter Tuning

In [54]:
y_pred = clf_svc.predict(X_test)

print("test", y_test[:10])
print("pred", y_pred[:10])

print(metrics.confusion_matrix(y_test,y_pred))
print("Precision Score:: ",metrics.precision_score(y_test,y_pred,average='weighted'))   
print("Recall Score:: ",metrics.recall_score(y_test,y_pred,average='weighted'))      
print("F1 Score:: ",metrics.f1_score(y_test,y_pred,average='weighted')) 

test [4 7 6 6 5 7 6 6 3 6]
pred [6 6 6 6 6 6 6 6 6 6]
[[   0    0    0    0    0    0    4    0    0]
 [   0    0    0    0    0    0   15    0    0]
 [   0    0    0    0    0    0   45    0    0]
 [   0    0    0    0    0    0  117    0    0]
 [   0    0    0    0    0    0  339    0    0]
 [   0    0    0    0    0    0  720    0    0]
 [   0    0    0    0    0    0 1027    0    0]
 [   0    0    0    0    0    0  535    0    0]
 [   0    0    0    0    0    0  100    0    0]]
Precision Score::  0.125240868604
Recall Score::  0.353893866299
F1 Score::  0.185008399435


C:\Users\Mardavkumar\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Mardavkumar\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [73]:
y_pred = clf_mnb.predict(X_test_mnb)

print("test", y_test[:10])
print("pred", y_pred[:10])

print(metrics.confusion_matrix(y_test_mnb,y_pred))
print("Precision Score:: ",metrics.precision_score(y_test_mnb,y_pred,average='weighted'))   
print("Recall Score:: ",metrics.recall_score(y_test_mnb,y_pred,average='weighted'))      
print("F1 Score:: ",metrics.f1_score(y_test_mnb,y_pred,average='weighted'))

test [6 5 8 5 6 7 5 6 6 4]
pred [5 6 8 5 8 6 7 4 6 5]
[[   0    9    2    0    0    0    0    0    3]
 [   0   28   27   15    7    3    1    2    4]
 [   0   11   36   23   31   41    1    6   31]
 [   0    2   42   41   76  181   17   17   54]
 [   0    1   25   48   70  629  127   75   96]
 [   0    0    9   20   58  795  692  164  133]
 [   0    0    1    4   21  326 1363  291  212]
 [   0    0    0    0    5   27  613  273  371]
 [   0    0    0    0    0    1   30   57  323]]
Precision Score::  0.370004542341
Recall Score::  0.38687095496
F1 Score::  0.356148256486


C:\Users\Mardavkumar\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Mardavkumar\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [70]:
y_pred = clf_knn.predict(X_test)

print("test", y_test[:10])
print("pred", y_pred[:10])

print(metrics.confusion_matrix(y_test,y_pred))
print("Precision Score:: ",metrics.precision_score(y_test,y_pred,average='weighted'))   
print("Recall Score:: ",metrics.recall_score(y_test,y_pred,average='weighted'))      
print("F1 Score:: ",metrics.f1_score(y_test,y_pred,average='weighted'))

test [6 5 8 5 6 7 5 6 6 4]
pred [6 6 8 4 4 6 6 4 6 4]
[[   2    9    1    0    1    1    0    0    0]
 [   1   33   28   16    6    3    0    0    0]
 [   1   16   49   53   33   19    6    2    1]
 [   0    4   35  118  144   95   28    6    0]
 [   0    5   25  115  324  419  156   26    1]
 [   0    3    5   56  315  886  532   68    6]
 [   0    0    4   15  115  725 1082  257   20]
 [   0    0    1    3   19  182  569  433   82]
 [   0    0    1    0    2   10   43  203  152]]
Precision Score::  0.41013434477
Recall Score::  0.406683397173
F1 Score::  0.40398390215


In [71]:
y_pred = clf_lr.predict(X_test)

print("test", y_test[:10])
print("pred", y_pred[:10])

print(metrics.confusion_matrix(y_test,y_pred))
print("Precision Score:: ",metrics.precision_score(y_test,y_pred,average='weighted'))   
print("Recall Score:: ",metrics.recall_score(y_test,y_pred,average='weighted'))      
print("F1 Score:: ",metrics.f1_score(y_test,y_pred,average='weighted'))


test [6 5 8 5 6 7 5 6 6 4]
pred [6 6 8 5 7 6 6 5 6 4]
[[   0   10    3    0    1    0    0    0    0]
 [   0   19   29   31    8    0    0    0    0]
 [   0   14   20   74   60   12    0    0    0]
 [   0    3    7   70  256   86    8    0    0]
 [   0    1    3   37  320  647   56    7    0]
 [   0    2    1    3   82 1145  598   40    0]
 [   0    0    0    0    7  274 1685  246    6]
 [   0    0    0    0    0    8  493  704   84]
 [   0    0    0    0    0    0    2  195  214]]
Precision Score::  0.534905341736
Recall Score::  0.551710474178
F1 Score::  0.533816822735


C:\Users\Mardavkumar\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Mardavkumar\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [72]:
y_pred_lir = clf_lir.predict(X_test_lir)

print("test",y_test_lir[:20])
print("pred", y_pred_lir[:20])

print("R2 score",metrics.r2_score(y_test_lir,y_pred_lir))
print("RMSE:: ",np.sqrt(metrics.mean_squared_error(y_test_lir, y_pred_lir)))
print("MSE:: ", metrics.mean_squared_error(y_test_lir, y_pred_lir))

test [ 4.   3.5  5.   3.5  4.   4.5  3.5  4.   4.   3.   3.5  3.   2.5  5.   4.5
  3.5  3.5  4.   3.5  3.5]
pred [ 3.9220558   3.64063108  5.21931989  3.44153266  3.78197047  4.26234294
  3.82135511  3.69632909  3.75181228  2.92571961  3.1518672   3.18871931
  2.59257826  4.80507159  4.46064339  3.10583086  3.68843538  3.79872847
  3.49112125  3.70361147]
R2 score 0.859165520359
RMSE::  0.272126023527
MSE::  0.0740525726804
